#!/usr/bin/perl
# SCRIPT: acctinfo
# PURPOSE: Get the username (cPanel/FTP) for domain name entered at command line
# AUTHOR: Peter Elsner <peter.elsner@cpanel.net>
# v1.0 - CREATED:  03/28/2014
# v1.1 - MODIFIED: 5/7/2014 - Added --listdbs & --listssls options to list any MySQL DB's and SSL's (Idea by Tristan Wallace) 
# v1.1.0 - MODIFIED: 5/8/2014 - Added -q switch to clear the screen (default is to not clear the screen) (Idea by Ryan Robson)
# v1.2 - MODIFIED: 5/18/2014 - Added additional switches --listsubs, --listaddons, --listparked, --listreseller (default [no switches] is to list everything) 
# v1.3 - MODIFIED: 6/01/2014 - Added --help switch to list the options. (Idea by Citizen Kepler)
# v1.3 - MODIFIED: 6/01/2014 - Added a count of all accounts in /etc/trueuserdomains.
# v1.4 - MODIFIED: 7/14/2014 - Added "use strict" and set all variables and arrays accordingly.
# v1.5 - MODIFIED: 7/14/2014 - Added postgresql databases and tables.
# V1.6 - MODIFIED: 7/27/2014 - BugFix - if PostGreSQL is not installed the psql command would fail
# V1.7 - MODIFIED: 8/22/2014 - BugFix - PostGreSQL can be installed and not running - psql call 
#        would fail. Fixed this.  
# V1.7 - MODIFIED: 8/22/2014 - Added PostGreSQL table size to output
# V1.7 - MODIFIED: 8/22/2014 - Added [Resolves to SAME] if domain resolves to same server IP.
# V1.8 - MODIFIED: 9/23/2014 - BugFix - Fixed SSL Certificate display (some SSL certs were not 
#			being found).
# V1.8 - MODIFIED: 9/23/2014 - BugFix - Fixed STARTDATE (was not being displayed)
# V1.8 - MODIFIED: 9/23/2014 - BugFix - Fixed display of sub/addon/parked domains (if only 1
#			of either was created, it would not show them).  

use strict;
my $VERSION="1.8;

use File::stat;
use Getopt::Long;

my $all = undef;
my $listdbs = undef;
my $listssls = undef;
my $listsubs = undef;
my $listaddons = undef;
my $listparked = undef;
my $listreseller = undef;
my $clearscreen = undef;
my $helpME = undef;

GetOptions(
   'listdbs' => \$listdbs,
   'listssls' => \$listssls,
   'listsubs' => \$listsubs,
   'listaddons' => \$listaddons,
   'listparked' => \$listparked,
   'listreseller' => \$listreseller,
   'help' => \$helpME,
   'q' => \$clearscreen,
);

if ($clearscreen) { 
	system("clear");
}
print "acctinfo - Version: " . $VERSION . "\n";
if ($helpME) { 
	&Usage;
}

$all=1 unless($listdbs or $listssls or $listsubs or $listaddons or $listparked or $listreseller or $helpME);

# Determine the correct HOME DIRECTORY by grabbing the HOMEDIR value
# from /etc/wwwacct.conf (one of cPanel's conf files)
my $IS_USERNAME=0;
my $HOMEDIR=qx[ cat /etc/wwwacct.conf | grep 'HOMEDIR' ];
my ($NAME,$VALUE)=(split(/\s+/,$HOMEDIR));
$HOMEDIR=$VALUE;
chomp($HOMEDIR);
my $SERVER_IP=qx[ cat /etc/wwwacct.conf | grep 'ADDR' ];
($NAME,$VALUE)=(split(/\s+/,$SERVER_IP));
$SERVER_IP=$VALUE;
chomp($SERVER_IP);

my $DOMAIN=@ARGV[0];
chomp($DOMAIN);
if ($DOMAIN eq "") {
	&Usage;
}
$DOMAIN=lc($DOMAIN);
my ($TheDomain,$TheExt)=(split(/\./,$DOMAIN));
if ($TheExt eq "") { 
	my $IS_USERNAME=1;
}

my $HOSTNAME=`hostname`;
chomp($HOSTNAME);
# First check trueuserdomains (for the main domain)
my @RESULT=qx[ grep $DOMAIN /etc/trueuserdomains ];
my $CNT=@RESULT;
if ($CNT==0) {    ## If not found there, then check userdomains (it could be addon/parked/sub domain)
	@RESULT=qx[ grep $DOMAIN /etc/userdomains ];
	$CNT=@RESULT;
	if ($CNT==0) {     ## If not found there either, then it's not on this server
		print "ERROR: $DOMAIN not found on $HOSTNAME\n";
		exit;
	}
}

my ($username)=(split(/\: /,@RESULT[0]))[1];
chomp($username);
# Now get the main domain from /etc/trueuserdomains using the $username
my @MAINDOMAIN=qx[ grep $username /etc/trueuserdomains ];
my ($MAINDOMAIN)=(split(/\: /,@MAINDOMAIN[0]))[0];
chomp($MAINDOMAIN);

# Check to see if the $username is in /var/cpanel/suspended directory (indicating user is suspended).
my $SUSP="";
if (-e("/var/cpanel/suspended/$username")) { 
	my $REASON=`cat /var/cpanel/suspended/$username`;
	$SUSP="NOTE: " . $username . " is suspended - " . $REASON . ".\n";
	chomp($REASON);
}

# Now read file /etc/userdatadomains into array
open(USERDATAFILE,"/etc/userdatadomains");
my @USERDATADOMAINS=<USERDATAFILE>;
close(USERDATAFILE);

# Now get all parked, addon and sub domains (if any)
my $IS_PARKED="";
my $IS_ADDON="";
my $IS_SUB="";
my @SUBDOMAINS="";
my $ACCT="";
foreach $ACCT(@USERDATADOMAINS) { 
	chomp($ACCT);
	if($ACCT =~ m/ $username/) { 
		if($ACCT =~ m/==sub==/) { 
			my ($sub_domain)=(split(/\s+/,$ACCT))[0];
			chop($sub_domain);
			push(@SUBDOMAINS, $sub_domain);
			if ($sub_domain eq $DOMAIN) { 
				$IS_SUB = "$DOMAIN is a sub domain of $MAINDOMAIN\n";
			}
		}
	}
}
# Now get all addon domains (if any)
my @ADDONDOMAINS="";
foreach $ACCT(@USERDATADOMAINS) { 
	chomp($ACCT);
	if($ACCT =~ m/ $username/) { 
		if($ACCT =~ m/==addon==/) { 
			my ($addon_domain)=(split(/\s+/,$ACCT))[0];
			chop($addon_domain);
			push(@ADDONDOMAINS, $addon_domain);
			if ($addon_domain eq $DOMAIN) { 
				$IS_ADDON = "$DOMAIN is an addon domain of $MAINDOMAIN\n";
			}
		}
	}
}
# Now get all parked domains (if any)
my @PARKEDDOMAINS="";
foreach $ACCT(@USERDATADOMAINS) { 
	chomp($ACCT);
	if($ACCT =~ m/ $username/) { 
		if($ACCT =~ m/==parked==/) { 
			my ($parked_domain)=(split(/\s+/,$ACCT))[0];
			chop($parked_domain);
			push(@PARKEDDOMAINS, $parked_domain);
			if ($parked_domain eq $DOMAIN) { 
				$IS_PARKED = "$DOMAIN is a parked domain of $MAINDOMAIN\n";
			}
		}
	}
}
# Now get all data from /var/cpanel/users/$username
open(USERDATA,"/var/cpanel/users/$username");
my @USERDATA=<USERDATA>;
close(USERDATA);
# Get package
my $USERLINE="";
my $PACKAGE="";
my $IPADDR="";
my $STARTDATE="";
my $STARTDATE2="";
foreach $USERLINE(@USERDATA) { 
	if ($USERLINE =~ m/PLAN/) { 
		($PACKAGE)=(split(/=/,$USERLINE))[1];
		last;
	}
}
chomp($PACKAGE);
# Get IP address
foreach $USERLINE(@USERDATA) { 
	if ($USERLINE =~ m/IP/) { 
		($IPADDR)=(split(/=/,$USERLINE))[1];
		last;
	}
}
chomp($IPADDR);
# Resolve the ip address of $MAINDOMAIN to see if it is pointing somewhere else
my $ResolvedIP=qx[ dig \@8.8.8.8 $MAINDOMAIN A +short ];
my $IPTYPE="shared";
my $RESOLVES_TO="";
chomp($ResolvedIP);
my $NXDOMAIN="";
if ($ResolvedIP eq "") { 
	$NXDOMAIN="Non Existant (NXDOMAIN)";
}
if ($ResolvedIP ne $IPADDR) { 
	$RESOLVES_TO = $MAINDOMAIN . " resolves to IP: $ResolvedIP $NXDOMAIN";
}
else { 
	$RESOLVES_TO = $MAINDOMAIN . " resolves to SAME ($ResolvedIP)";
	$IPTYPE="shared";
	if($IPADDR ne $SERVER_IP) { 
		$IPTYPE="dedicated";
	}
}
# Get start date (when account was created)
foreach $USERLINE(@USERDATA) { 
	if ($USERLINE =~ m/STARTDATE/) { 
		($STARTDATE2)=(split(/=/,$USERLINE))[1];
		my $STARTDATE=scalar localtime($STARTDATE2);
		last;
	}
}
# See if this user is it's own owner (if not it is owned by a reseller)
my $RO_TEXT="";
my $REAL_OWNER="";
foreach $USERLINE(@USERDATA) { 
	if ($USERLINE =~ m/^OWNER/) { 
		($REAL_OWNER)=(split(/=/,$USERLINE))[1];
		chomp($REAL_OWNER);
		if ($REAL_OWNER ne $username and $REAL_OWNER ne "root") { 
			my $RO_TEXT=" (Which is under the reseller: $REAL_OWNER)";
		}
		last;
	}
}
# Check if main domain (username) is a reseller.
my $Is_Reseller=0;
my $acct="";
my @OWNEDBYRESELLER=undef;
if (-e("/var/cpanel/root.accts")) { 
	open(accts,"/var/cpanel/root.accts");
	my @AllAccts=<accts>;
	close(accts);
	shift @AllAccts;
	foreach $acct(@AllAccts) { 
		chomp($acct);
		my ($resellersdomain,$OWNER)=(split(/,/,$acct))[0,10];
		if ($OWNER eq $username or $OWNER eq $REAL_OWNER and ($REAL_OWNER ne "root")) { 
			my $Is_Reseller=1;
			push(@OWNEDBYRESELLER,$resellersdomain);
		}
	}
}
# Get IP address from .lastlogin file (if it exists)
my $LastLoginIP="";
my $AccessDate="";
if (-e("$HOMEDIR/$username/.lastlogin")) { 
	$LastLoginIP=qx[ cat $HOMEDIR/$username/.lastlogin ];
	my $nst=stat("$HOMEDIR/$username/.lastlogin");
	my $mtime=$nst->mtime;
	$AccessDate=scalar localtime($mtime);
	chomp($LastLoginIP);
}

if ($IS_USERNAME) { 
	print "\n";
}
else { 
	print "\nThe user name for $DOMAIN is: $username\n";
}
my $TOTAL_DOMAINS=qx[ cat /etc/trueuserdomains | wc -l ];
chomp($TOTAL_DOMAINS);
print "The main domain is $MAINDOMAIN $RO_TEXT\n";
print "There are $TOTAL_DOMAINS total domains on this server.\n";
print "$IS_PARKED\n" unless($IS_PARKED eq "");
print "$IS_ADDON\n" unless($IS_ADDON eq "");
print "$IS_SUB\n" unless($IS_SUB eq "");
print $MAINDOMAIN . " has the " . $PACKAGE . " hosting package\n";
print $MAINDOMAIN . " has a " . $IPTYPE . " IP address of " . $IPADDR . "\n";
print $RESOLVES_TO . "\n" unless($RESOLVES_TO eq "");
if($LastLoginIP) { 
	print $MAINDOMAIN . " last logged in to cPanel from IP: " . $LastLoginIP . " On: " . $AccessDate . "\n";
}

my $STARTDATE=scalar localtime($STARTDATE2);
chomp($STARTDATE);
print $MAINDOMAIN . " has been a customer since " . $STARTDATE . "\n";

if ($SUSP) { 
	print "==============================================================================================\n";
	print $SUSP;
}
# DOMAIN INFO (PARKED, ADDON, SUB)
shift @SUBDOMAINS;
shift @ADDONDOMAINS;
shift @PARKEDDOMAINS;
my $subcnt=@SUBDOMAINS;
my $addoncnt=@ADDONDOMAINS;
my $parkcnt=@PARKEDDOMAINS;
my $SUB="";
my $PARK="";
my $ADDON="";
if ($subcnt+$addoncnt+$parkcnt>1 and ($all or $listsubs or $listaddons or $listparked)) { 
	print "The following are associated with $MAINDOMAIN ($username)\n";
	print "==============================================================================================\n";
}
if ($all or $listsubs) { 
	print "Sub Domains:\n";
	if ($subcnt > 0 and ($all or $listsubs)) { 
		foreach $SUB(@SUBDOMAINS) { 
			chomp($SUB);
			print "\t \\_ $SUB\n";
		}
		print "==============================================================================================\n";
	}
	else { 
		print "No Sub Domains found for $MAINDOMAIN ($username)\n";
	}
}

if ($all or $listaddons) { 
	print "Addon Domains:\n";
	if ($addoncnt > 0 and ($all or $listaddons)) { 
		foreach $ADDON(@ADDONDOMAINS) { 
			chomp($ADDON);
			print "\t \\_ $ADDON\n";
		}
		print "==============================================================================================\n";
	}
else { 
		print "No Addon Domains found for $MAINDOMAIN ($username)\n";
	}
}

if ($all or $listparked) { 
	if ($parkcnt > 0 and ($all or $listparked)) { 
		print "Parked Domains:\n";
		foreach $PARK(@PARKEDDOMAINS) { 
			chomp($PARK);
			print "\t \\_ $PARK\n";
		}
		print "==============================================================================================\n";
	}
	else { 
		print "No Parked Domains found for $MAINDOMAIN ($username)\n";
	}
}

# RESELLER INFO
if ($listreseller or $all) { 
	my $ResellersDomain="";
	if ($Is_Reseller) { 
		print "==============================================================================================\n";
		if ($RO_TEXT) { 
			print "The " . $REAL_OWNER . " reseller also has the following other domains associated with it\n";
		}
		else { 
			print $MAINDOMAIN . " is a reseller and has the following accounts under it\n";
		}
		foreach $ResellersDomain(@OWNEDBYRESELLER) { 
			chomp($ResellersDomain);
			print "\t \\_ $ResellersDomain\n";
		}
	}
	else { 
		print "==============================================================================================\n";
		print "No Reseller information found for $MAINDOMAIN ($username)\n";
	}
}
# MySQL INFO
if ($listdbs or $all) { 
	my @USERDBS=undef;
	my @DBSIZE=undef;
	my $USERDB="";
	my $SIZEOFDB="";
	my $DBNAME="";
	my $DBSIZE="";
	print "==============================================================================================\n";
	@USERDBS=qx[ echo "show databases like '$username%'" | mysql ];
	splice(@USERDBS,0,1);
	my $DBCNT=@USERDBS;
	if ($DBCNT == 0) {
		print "No MySQL databases found for $MAINDOMAIN ($username)\n";
	}
	else { 
		print "The following MySQL databases can be found under: $username\n";
		foreach $USERDB(@USERDBS) {
			chomp($USERDB);
			@DBSIZE = qx[ echo "select table_schema, sum(data_length + index_length) / 1024 / 1024 FROM information_schema.TABLES where table_schema = '$USERDB' GROUP By table_schema;" | mysql ];
			splice(@DBSIZE,0,1);
			chomp(@DBSIZE);
			my $num=@DBSIZE;
			if ($num == 0) {
				print "\t \\_ $USERDB has no tables.\n";
				next;
			}
			foreach $SIZEOFDB(@DBSIZE) {
				chomp($SIZEOFDB);
				($DBNAME,$DBSIZE)=(split(/\s+/,$SIZEOFDB));
				chomp($DBNAME);
				chomp($DBSIZE);
				$DBSIZE=sprintf("%.2f", $DBSIZE);
				print "\t \\_ $DBNAME ($DBSIZE MB)\n";
			}
		}
	}
	print "\n";
   # PostGreSQL INFO
   my $psql_running = 0; if (qx[ ps ax | grep postgres | grep -v grep ]) { $psql_running = 1; }
   if (-e("/usr/bin/psql") and $psql_running) {    ## PostGreSQL is installed and running
   	my @PSQLDBS=undef;
	   my $PgDb="";
	   @PSQLDBS=qx[ /usr/bin/psql -U postgres -c "SELECT datname FROM pg_catalog.pg_database WHERE datistemplate='f' AND datname !='postgres'" | grep -v '\-' | grep -v 'datname' | grep -v ' row' ];
	   pop(@PSQLDBS);
	   my $PgDbCount=@PSQLDBS;
	   if ($PgDbCount == 0) { 
		   print "No PostGreSQL databases found for $MAINDOMAIN ($username)\n";
	   }
	   else { 
		   print "The following PostGreSQL databases can be found under: $username\n";
		   my $pg_table="";
		   my @PG_TABLES=undef;
		   foreach $PgDb(@PSQLDBS) { 
			   chomp($PgDb);
			   $PgDb=substr($PgDb,1);
			   $pg_table=qx[ psql -U postgres $PgDb -c "SELECT relname FROM pg_catalog.pg_class WHERE relkind = 'r' AND pg_get_userbyid(relowner) = '$username'" | grep -v '\-' | grep -v 'relname' | grep -v ' row' ];
			   chomp($pg_table);
			   chomp($pg_table);
			   $pg_table =~ s/^\s+//;
			   $pg_table =~ s/\s+/, /g;
			   if ($pg_table eq "") { 
				   print "\t \\_ $PgDb - has no tables\n";
			   }
			   else { 
				   print "\t \\_ $PgDb\n";
               my ($pg_table_size) = (split(/\|/,qx[ psql -U postgres -d $PgDb -c "\\dt+" | grep '$pg_table' ]))[4];
				   print "\t\t \\_ $pg_table ($pg_table_size)\n";
			   }
		   }
	   }
   }
   else { 
      print "PostGreSQL server is not installed (or running) on $HOSTNAME\n";
   }
}
# SSL INFO
if ($listssls or $all) { 
	my $SSLSFOUND=0;
	my $sslline="";
	my $ssldomain="";
	my $ssldomaincrap="";
	my @SSLDATA=undef;
	print "==============================================================================================\n";
	@SSLDATA = qx[ ls /var/cpanel/userdata/$username/*_SSL ];
	my $sslcnt=@SSLDATA;
	if ($sslcnt>0) { 
		print "SSL Certificates installed under $MAINDOMAIN ($username)\n";
		$SSLSFOUND=1;
	}
	else { 
		print "No SSL Certificates found for $MAINDOMAIN ($username)\n";
	} 
	if ($SSLSFOUND) { 
		foreach $sslline(@SSLDATA) { 
			chomp($sslline);
			($ssldomaincrap)=(split(/\//,$sslline))[5];
			($ssldomain)=(split(/_/,$ssldomaincrap))[0];
			print "\t \\_ $ssldomain\n";
		}
	}
}
print "==============================================================================================\n";

sub Usage { 
   print "Usage: $0 [options] domainname.tld or cPUsername\n\n";
   print "Example: $0 --listdbs somedomain.net\n";
   print "\t Lists any MySQL  databases (and their sizes) as well as any PostGreSQL databases for somedomain.net\n";
   print "$0 --listsubs cptestdo\n";
   print "\t Lists all sub domains under the cptestdo user name.\n";
   print "$0 --listaddons cptestdomain.net\n";
   print "\t Lists all addon domains under the cptestdomain.net domain name.\n";
   print "$0 --listparked cptestdomain.net\n";
   print "\t Lists all parked domains under the cptestdomain.net domain name.\n";
   print "$0 --listreseller cptestdo\n";
   print "\t Lists reseller information and domains under the cptestdo user name.\n";
   print "$0 --listssls cptestdomain.net\n";
   print "\t Lists any SSL's under the cptestdomain.net domain name.\n";
	exit;
}

exit;
