# The name of the plugin
name=acctinfo

# Service that will run the plugin/app
service=whostmgr

# Url 
url=/cgi/acctinfo/acctinfo.cgi

# User to run the plugin as (root)
user=root

# URL where the plugin program will be stored/called from (relative to /usr/local/cpanel/docroot/)
url=/cgi/acctinfo

# Required ACL's
acls=software-acctinfo

# Display name within the WHM (Plugins section)
displayname=Account Information - <b>acctinfo</b>

# URL to show in WHM (again, relative to where the plugin/app is installed)
entryurl=acctinfo/acctinfo.cgi

# Icon that will show up in WHM => Plugins section
icon=acctinfo_logo.png

upgradecall=/usr/local/cpanel/whostmgr/docroot/acctinfo/acctinfo/upgrade.sh

# Target for opening screen in same location (not a new window)
target=_self
